spring:
  datasource:
    url: jdbc:mysql:///prodcut
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: stu_service
  registry:
    address: zookeeper://192.168.65.129:2181
server:
  port: 8181
